### ISSUE TITLE
PEER Correction 

### ISSUE THREAD

**Issue by jcgrenier** [broadinstitute/gtex-v8#1]
Hello all,

We are currently calculating PEER factors for GTEx v8. As pre-processing, we applied almost the same filter that you did, excepting for the TPM filter, and sample selection. and the normalisation method is also different. Anyway, we wanted to redo PEER since the samples are in the end not the same as the complete dataset.

With 1000 iterations, half of the tissues did not converge. We decided to run them again with a larger amount of permitted iterations (100000). It’s been running for almost a month so far and it's still not converging. The completed iterations varies from 1500 to over 9000 for now. 

We  were wondering if it is normal that it takes so much time to converge.
Thanks a lot for you help.
Best,

Jean-Christophe

**Comment by francois-a** [comment]
Hi,

Are you using the same pre-processing steps as described in [eqtl_prepare_expression.py](https://github.com/broadinstitute/gtex-pipeline/blob/master/qtl/src/eqtl_prepare_expression.py)? As long as an appropriate between-sample correction is applied, and the expression values are either inverse normal or log transformed, the calculation should converge in a few hundred iterations or faster.

**Comment by jcgrenier** [comment]
Hello @francois-a ,

Our student that is working on it will verify. As long as it's supposed to converge, I guess we will keep looking for a fix on our side. Thanks for your answer!
