### ISSUE TITLE
Data for Supplementary Figure S34

### ISSUE THREAD

**Issue by ape4fld** [broadinstitute/gtex-v8#5]
Hello,

I would like to know if you have made available the correlation data shown as heatmap plots on the Supplementary Figure S34 (i.e. pairwise tissue sharing). I am especially interested in the correlation data for panels A, B and F. 

Thanks in advance!

Frida

**Comment by francois-a** [comment]
Hi,

Yes, the matrices are available [here](https://github.com/broadinstitute/gtex-v8/tree/master/data/supplement). This is fig. S41 in the [published version](https://www.science.org/doi/suppl/10.1126/science.aaz1776/suppl_file/aaz1776_aguet_sm.pdf).

**Comment by ape4fld** [comment]
Great, thanks!
